# Generated by Django 4.2.11 on 2026-03-06 18:55

from django.db import migrations, models
import users.models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={"verbose_name": "User", "verbose_name_plural": "Users"},
        ),
        migrations.AlterModelOptions(
            name="userskill",
            options={"ordering": ["-proficiency_level", "skill_name"]},
        ),
        migrations.RemoveField(
            model_name="careergoal",
            name="target_salary_range",
        ),
        migrations.AddField(
            model_name="careergoal",
            name="completed_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="careergoal",
            name="is_completed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="analyzed",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="resume",
            name="ats_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="resume",
            name="match_score",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="portfolio_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="usereducation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userexperience",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="userskill",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="careergoal",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="resume",
            name="file",
            field=models.FileField(upload_to=users.models.resume_upload_path),
        ),
        migrations.AlterField(
            model_name="usereducation",
            name="field_of_study",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="userexperience",
            name="skills_used",
            field=models.ManyToManyField(blank=True, to="users.userskill"),
        ),
        migrations.AlterField(
            model_name="userskill",
            name="last_used",
            field=models.IntegerField(default=2026),
        ),
        migrations.AddIndex(
            model_name="careergoal",
            index=models.Index(
                fields=["user", "is_active"], name="career_goal_user_id_11b724_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="resume",
            index=models.Index(
                fields=["user", "is_primary"], name="resumes_user_id_9373dc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["email"], name="users_email_4b85f2_idx"),
        ),
        migrations.AddIndex(
            model_name="user",
            index=models.Index(fields=["created_at"], name="users_created_6541e9_idx"),
        ),
        migrations.AddIndex(
            model_name="usereducation",
            index=models.Index(
                fields=["user", "is_current"], name="user_educat_user_id_1f6dcc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userexperience",
            index=models.Index(
                fields=["user", "is_current"], name="user_experi_user_id_99a19e_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["user", "skill_name"], name="user_skills_user_id_2d10d7_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userskill",
            index=models.Index(
                fields=["proficiency_level"], name="user_skills_profici_7a0f4a_idx"
            ),
        ),
    ]
