# Generated by Django 4.2.11 on 2026-03-09 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_alter_user_options_alter_userskill_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="resume",
            name="file_type",
            field=models.CharField(max_length=100),
        ),
    ]
