# Generated by Django 4.2.11 on 2026-03-11 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_alter_resume_file_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="userskill",
            name="is_learning",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="userskill",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
