# Generated by Django 4.2.11 on 2026-02-07 06:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Roadmap",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField(blank=True, null=True)),
                ("target_role", models.CharField(max_length=100)),
                (
                    "target_industry",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("generated_by_ai", models.BooleanField(default=True)),
                ("total_duration_months", models.IntegerField(default=12)),
                (
                    "difficulty_level",
                    models.CharField(
                        choices=[
                            ("beginner", "Beginner"),
                            ("intermediate", "Intermediate"),
                            ("advanced", "Advanced"),
                        ],
                        default="intermediate",
                        max_length=20,
                    ),
                ),
                ("current_step_index", models.IntegerField(default=0)),
                ("completion_percentage", models.FloatField(default=0.0)),
                ("is_completed", models.BooleanField(default=False)),
                ("skill_gap_analysis", models.JSONField(default=dict)),
                ("market_insights", models.JSONField(default=dict)),
                ("salary_projection", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                ("last_accessed", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="roadmaps",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "roadmaps",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RoadmapStep",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("step_number", models.IntegerField()),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "step_type",
                    models.CharField(
                        choices=[
                            ("learning", "Learning"),
                            ("project", "Project"),
                            ("certification", "Certification"),
                            ("networking", "Networking"),
                            ("job_application", "Job Application"),
                            ("interview_prep", "Interview Preparation"),
                        ],
                        default="learning",
                        max_length=50,
                    ),
                ),
                ("estimated_duration_hours", models.IntegerField(default=40)),
                ("recommended_timeline", models.CharField(max_length=100)),
                ("resources", models.JSONField(default=list)),
                ("skills_to_develop", models.JSONField(default=list)),
                ("is_completed", models.BooleanField(default=False)),
                ("completion_date", models.DateTimeField(blank=True, null=True)),
                ("user_notes", models.TextField(blank=True, null=True)),
                ("difficulty_rating", models.IntegerField(blank=True, null=True)),
                ("actual_duration_hours", models.IntegerField(blank=True, null=True)),
                ("satisfaction_score", models.IntegerField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "depends_on",
                    models.ManyToManyField(blank=True, to="roadmap.roadmapstep"),
                ),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="steps",
                        to="roadmap.roadmap",
                    ),
                ),
            ],
            options={
                "db_table": "roadmap_steps",
                "ordering": ["roadmap", "step_number"],
                "unique_together": {("roadmap", "step_number")},
            },
        ),
        migrations.CreateModel(
            name="ProgressUpdate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "update_type",
                    models.CharField(
                        choices=[
                            ("step_completed", "Step Completed"),
                            ("step_started", "Step Started"),
                            ("note_added", "Note Added"),
                            ("resource_completed", "Resource Completed"),
                            ("roadmap_created", "Roadmap Created"),
                            ("roadmap_modified", "Roadmap Modified"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField()),
                ("metadata", models.JSONField(default=dict)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="progress_updates",
                        to="roadmap.roadmap",
                    ),
                ),
                (
                    "step",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.roadmapstep",
                    ),
                ),
            ],
            options={
                "db_table": "progress_updates",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="LearningResource",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "resource_type",
                    models.CharField(
                        choices=[
                            ("course", "Online Course"),
                            ("book", "Book"),
                            ("article", "Article"),
                            ("video", "Video"),
                            ("tutorial", "Tutorial"),
                            ("documentation", "Documentation"),
                            ("podcast", "Podcast"),
                            ("tool", "Tool/Software"),
                        ],
                        max_length=50,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("url", models.URLField()),
                ("description", models.TextField(blank=True, null=True)),
                (
                    "duration_estimate",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "difficulty_level",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("is_free", models.BooleanField(default=True)),
                ("platform", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "completion_status",
                    models.CharField(
                        choices=[
                            ("not_started", "Not Started"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("skipped", "Skipped"),
                        ],
                        default="not_started",
                        max_length=20,
                    ),
                ),
                ("user_rating", models.IntegerField(blank=True, null=True)),
                ("completed_date", models.DateTimeField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "step",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="learning_resources",
                        to="roadmap.roadmapstep",
                    ),
                ),
            ],
            options={
                "db_table": "learning_resources",
            },
        ),
        migrations.CreateModel(
            name="SkillDevelopment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("skill_name", models.CharField(max_length=100)),
                ("current_level", models.CharField(max_length=20)),
                ("target_level", models.CharField(max_length=20)),
                ("progress_percentage", models.FloatField(default=0.0)),
                ("resources_completed", models.IntegerField(default=0)),
                ("total_resources", models.IntegerField(default=0)),
                ("last_practiced", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "roadmap",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="roadmap.roadmap",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="skill_development",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "skill_development",
                "unique_together": {("user", "skill_name", "roadmap")},
            },
        ),
    ]
