# Generated by Django 4.2.11 on 2026-03-06 18:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("roadmap", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="learningresource",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="learningresource",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="roadmapstep",
            name="recommended_timeline",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddIndex(
            model_name="learningresource",
            index=models.Index(
                fields=["step", "completion_status"],
                name="learning_re_step_id_506d01_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="progressupdate",
            index=models.Index(
                fields=["roadmap", "-created_at"], name="progress_up_roadmap_8242cf_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["user", "-created_at"], name="roadmaps_user_id_4e957f_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["target_role"], name="roadmaps_target__f884ef_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmap",
            index=models.Index(
                fields=["is_completed"], name="roadmaps_is_comp_dd8e08_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapstep",
            index=models.Index(
                fields=["roadmap", "step_number"], name="roadmap_ste_roadmap_6193b4_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="roadmapstep",
            index=models.Index(
                fields=["is_completed"], name="roadmap_ste_is_comp_4124ad_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="skilldevelopment",
            index=models.Index(
                fields=["user", "skill_name"], name="skill_devel_user_id_40277a_idx"
            ),
        ),
    ]
