# Generated by Django 4.2.11 on 2026-03-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ai_services", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="aiinteraction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("chat", "Chat"),
                    ("question", "Question"),
                    ("feedback", "Feedback"),
                    ("analysis_request", "Analysis Request"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="airecommendation",
            name="recommendation_type",
            field=models.CharField(
                choices=[
                    ("skill", "Skill Recommendation"),
                    ("course", "Course Recommendation"),
                    ("job", "Job Recommendation"),
                    ("career", "Career Path Recommendation"),
                    ("resource", "Resource Recommendation"),
                ],
                max_length=50,
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_analyses_user_id_ee7718_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="aianalysis",
            index=models.Index(fields=["status"], name="ai_analyses_status_6e3eeb_idx"),
        ),
        migrations.AddIndex(
            model_name="aiinteraction",
            index=models.Index(
                fields=["user", "-created_at"], name="ai_interact_user_id_346abc_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="airecommendation",
            index=models.Index(
                fields=["user", "status"], name="ai_recommen_user_id_d6b647_idx"
            ),
        ),
    ]
